stages:
  - lint

default:
  interruptible: true

# Run pipelines on MRs and on pushes to main and protocol release branches
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - when: never

.validate_yaml_base:
  stage: lint
  image: python:3.11
  before_script:
    - pip install --no-cache-dir yamllint
    - cd protocol
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - changes:
        - protocol/**

validate_yaml:
  extends: .validate_yaml_base
  script:
    - yamllint .golangci.yml .github/workflows/**.yml buf.work.yaml

.golangci_lint_base:
  stage: lint
  image: golang:1.23
  before_script:
    - cd protocol
  cache:
    key: "${CI_JOB_NAME}"
    policy: pull-push
    paths:
      - /go/pkg/mod
      - /go/bin
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - changes:
        - protocol/**

golangci_lint:
  extends: .golangci_lint_base
  script:
    - make lint