stages:
  - lint

# Workflow triggers (equivalent to GitHub on: push / pull_request)
workflow:
  rules:
    # Run on merge requests (similar to pull_request)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run on push to main or release/protocol/v* branches
    - if: '$CI_COMMIT_BRANCH =~ /^main$/ || $CI_COMMIT_BRANCH =~ /^release\/protocol\/v[0-9]+(\.[0-9]+)?(\.x)?$/'
    - when: never

# --- Job 1: validate-yaml ---
validate_yaml:
  stage: lint
  image: python:3.11
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - protocol/**/*
  before_script:
    - pip install --no-cache-dir yamllint
    - cd protocol
  script:
    - yamllint .golangci.yml .github/workflows/**.yml buf.work.yaml

# --- Job 2: golangci-lint ---
golangci_lint:
  stage: lint
  image: vindax-dev   # custom image with Go, make, golangci-lint, etc.
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - protocol/**/*
  before_script:
    - cd protocol
  script:
    - make lint
