FROM vindax-base

COPY ./testing/snapshotting/snapshot.sh /vindax/snapshot.sh

RUN go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@v1.5.0
RUN apk add --no-cache bash jq aws-cli

ENTRYPOINT ["/vindax/snapshot.sh"]
