// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vindax/affiliates/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Message to register a referee-affiliate relationship
type MsgRegisterAffiliate struct {
	// Address of the referee
	Referee string `protobuf:"bytes,1,opt,name=referee,proto3" json:"referee,omitempty"`
	// Address of the affiliate
	Affiliate string `protobuf:"bytes,2,opt,name=affiliate,proto3" json:"affiliate,omitempty"`
}

func (m *MsgRegisterAffiliate) Reset()         { *m = MsgRegisterAffiliate{} }
func (m *MsgRegisterAffiliate) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAffiliate) ProtoMessage()    {}
func (*MsgRegisterAffiliate) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{0}
}
func (m *MsgRegisterAffiliate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAffiliate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAffiliate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAffiliate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAffiliate.Merge(m, src)
}
func (m *MsgRegisterAffiliate) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAffiliate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAffiliate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAffiliate proto.InternalMessageInfo

// Response to MsgRegisterAffiliate
type MsgRegisterAffiliateResponse struct {
}

func (m *MsgRegisterAffiliateResponse) Reset()         { *m = MsgRegisterAffiliateResponse{} }
func (m *MsgRegisterAffiliateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAffiliateResponse) ProtoMessage()    {}
func (*MsgRegisterAffiliateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{1}
}
func (m *MsgRegisterAffiliateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAffiliateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAffiliateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAffiliateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAffiliateResponse.Merge(m, src)
}
func (m *MsgRegisterAffiliateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAffiliateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAffiliateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAffiliateResponse proto.InternalMessageInfo

// Message to update affiliate tiers
type MsgUpdateAffiliateTiers struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Updated affiliate tiers information
	Tiers AffiliateTiers `protobuf:"bytes,2,opt,name=tiers,proto3" json:"tiers"`
}

func (m *MsgUpdateAffiliateTiers) Reset()         { *m = MsgUpdateAffiliateTiers{} }
func (m *MsgUpdateAffiliateTiers) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateTiers) ProtoMessage()    {}
func (*MsgUpdateAffiliateTiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{2}
}
func (m *MsgUpdateAffiliateTiers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateTiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateTiers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateTiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateTiers.Merge(m, src)
}
func (m *MsgUpdateAffiliateTiers) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateTiers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateTiers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateTiers proto.InternalMessageInfo

func (m *MsgUpdateAffiliateTiers) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateTiers) GetTiers() AffiliateTiers {
	if m != nil {
		return m.Tiers
	}
	return AffiliateTiers{}
}

// Response to MsgUpdateAffiliateTiers
type MsgUpdateAffiliateTiersResponse struct {
}

func (m *MsgUpdateAffiliateTiersResponse) Reset()         { *m = MsgUpdateAffiliateTiersResponse{} }
func (m *MsgUpdateAffiliateTiersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateTiersResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateTiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{3}
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateTiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateTiersResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateTiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateTiersResponse proto.InternalMessageInfo

// Message to update affiliate whitelist
type MsgUpdateAffiliateWhitelist struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Updated affiliate whitelist information
	Whitelist AffiliateWhitelist `protobuf:"bytes,2,opt,name=whitelist,proto3" json:"whitelist"`
}

func (m *MsgUpdateAffiliateWhitelist) Reset()         { *m = MsgUpdateAffiliateWhitelist{} }
func (m *MsgUpdateAffiliateWhitelist) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateWhitelist) ProtoMessage()    {}
func (*MsgUpdateAffiliateWhitelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{4}
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateWhitelist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateWhitelist.Merge(m, src)
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateWhitelist) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateWhitelist.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateWhitelist proto.InternalMessageInfo

func (m *MsgUpdateAffiliateWhitelist) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateWhitelist) GetWhitelist() AffiliateWhitelist {
	if m != nil {
		return m.Whitelist
	}
	return AffiliateWhitelist{}
}

// Response to MsgUpdateAffiliateWhitelist
type MsgUpdateAffiliateWhitelistResponse struct {
}

func (m *MsgUpdateAffiliateWhitelistResponse) Reset()         { *m = MsgUpdateAffiliateWhitelistResponse{} }
func (m *MsgUpdateAffiliateWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateWhitelistResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{5}
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse proto.InternalMessageInfo

// Message to update affiliate program parameters
type MsgUpdateAffiliateParameters struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Affiliate program parameters
	AffiliateParameters AffiliateParameters `protobuf:"bytes,2,opt,name=affiliate_parameters,json=affiliateParameters,proto3" json:"affiliate_parameters"`
}

func (m *MsgUpdateAffiliateParameters) Reset()         { *m = MsgUpdateAffiliateParameters{} }
func (m *MsgUpdateAffiliateParameters) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateParameters) ProtoMessage()    {}
func (*MsgUpdateAffiliateParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{6}
}
func (m *MsgUpdateAffiliateParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateParameters.Merge(m, src)
}
func (m *MsgUpdateAffiliateParameters) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateParameters.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateParameters proto.InternalMessageInfo

func (m *MsgUpdateAffiliateParameters) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateParameters) GetAffiliateParameters() AffiliateParameters {
	if m != nil {
		return m.AffiliateParameters
	}
	return AffiliateParameters{}
}

// Response to MsgUpdateAffiliateParameters
type MsgUpdateAffiliateParametersResponse struct {
}

func (m *MsgUpdateAffiliateParametersResponse) Reset()         { *m = MsgUpdateAffiliateParametersResponse{} }
func (m *MsgUpdateAffiliateParametersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateParametersResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{7}
}
func (m *MsgUpdateAffiliateParametersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateParametersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateParametersResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateParametersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateParametersResponse proto.InternalMessageInfo

// Message to update affiliate overrides
type MsgUpdateAffiliateOverrides struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Addresses that automatically have the maximum affiliate tier
	AffiliateOverrides AffiliateOverrides `protobuf:"bytes,2,opt,name=affiliate_overrides,json=affiliateOverrides,proto3" json:"affiliate_overrides"`
}

func (m *MsgUpdateAffiliateOverrides) Reset()         { *m = MsgUpdateAffiliateOverrides{} }
func (m *MsgUpdateAffiliateOverrides) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateOverrides) ProtoMessage()    {}
func (*MsgUpdateAffiliateOverrides) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{8}
}
func (m *MsgUpdateAffiliateOverrides) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateOverrides) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateOverrides.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateOverrides) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateOverrides.Merge(m, src)
}
func (m *MsgUpdateAffiliateOverrides) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateOverrides) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateOverrides.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateOverrides proto.InternalMessageInfo

func (m *MsgUpdateAffiliateOverrides) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateOverrides) GetAffiliateOverrides() AffiliateOverrides {
	if m != nil {
		return m.AffiliateOverrides
	}
	return AffiliateOverrides{}
}

// Response to MsgUpdateAffiliateOverrides
type MsgUpdateAffiliateOverridesResponse struct {
}

func (m *MsgUpdateAffiliateOverridesResponse) Reset()         { *m = MsgUpdateAffiliateOverridesResponse{} }
func (m *MsgUpdateAffiliateOverridesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateOverridesResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateOverridesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a9d0659487269, []int{9}
}
func (m *MsgUpdateAffiliateOverridesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateOverridesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateOverridesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateOverridesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateOverridesResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateOverridesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateOverridesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateOverridesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateOverridesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterAffiliate)(nil), "vindax.affiliates.MsgRegisterAffiliate")
	proto.RegisterType((*MsgRegisterAffiliateResponse)(nil), "vindax.affiliates.MsgRegisterAffiliateResponse")
	proto.RegisterType((*MsgUpdateAffiliateTiers)(nil), "vindax.affiliates.MsgUpdateAffiliateTiers")
	proto.RegisterType((*MsgUpdateAffiliateTiersResponse)(nil), "vindax.affiliates.MsgUpdateAffiliateTiersResponse")
	proto.RegisterType((*MsgUpdateAffiliateWhitelist)(nil), "vindax.affiliates.MsgUpdateAffiliateWhitelist")
	proto.RegisterType((*MsgUpdateAffiliateWhitelistResponse)(nil), "vindax.affiliates.MsgUpdateAffiliateWhitelistResponse")
	proto.RegisterType((*MsgUpdateAffiliateParameters)(nil), "vindax.affiliates.MsgUpdateAffiliateParameters")
	proto.RegisterType((*MsgUpdateAffiliateParametersResponse)(nil), "vindax.affiliates.MsgUpdateAffiliateParametersResponse")
	proto.RegisterType((*MsgUpdateAffiliateOverrides)(nil), "vindax.affiliates.MsgUpdateAffiliateOverrides")
	proto.RegisterType((*MsgUpdateAffiliateOverridesResponse)(nil), "vindax.affiliates.MsgUpdateAffiliateOverridesResponse")
}

func init() { proto.RegisterFile("vindax/affiliates/tx.proto", fileDescriptor_961a9d0659487269) }

var fileDescriptor_961a9d0659487269 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x77, 0xb4, 0x2a, 0x19, 0x41, 0xe8, 0xba, 0xd0, 0x74, 0x95, 0x8d, 0x8d, 0xb6, 0x4a,
	0xa1, 0x3b, 0x18, 0xa1, 0x42, 0xd1, 0x43, 0x73, 0xf3, 0x10, 0x94, 0xf8, 0x0b, 0x44, 0x08, 0xd3,
	0xec, 0x64, 0x33, 0x90, 0x64, 0x96, 0x99, 0xe9, 0xda, 0x5e, 0x0b, 0x82, 0x47, 0x8f, 0x1e, 0xf3,
	0x27, 0xf4, 0xe0, 0x7f, 0xe0, 0xc1, 0x1e, 0x8b, 0x27, 0x4f, 0x22, 0xc9, 0x41, 0xff, 0x0a, 0x91,
	0xec, 0x8f, 0x19, 0xea, 0x6e, 0xb6, 0xdb, 0x7a, 0xca, 0x66, 0xdf, 0xf7, 0x7d, 0xdf, 0xfb, 0xcc,
	0x9b, 0xd9, 0x81, 0x76, 0x48, 0x47, 0x1e, 0xde, 0x43, 0xb8, 0xd7, 0xa3, 0x03, 0x8a, 0x25, 0x11,
	0x48, 0xee, 0xb9, 0x01, 0x67, 0x92, 0x99, 0x8b, 0x71, 0xcc, 0xd5, 0x31, 0x7b, 0xb9, 0xcb, 0xc4,
	0x90, 0x89, 0x4e, 0x24, 0x40, 0xf1, 0x9f, 0x58, 0x6d, 0x5b, 0x3e, 0xf3, 0x59, 0xfc, 0x7e, 0xf6,
	0x94, 0xbc, 0xad, 0x67, 0xfd, 0xf5, 0x63, 0xa2, 0x59, 0x8a, 0x7d, 0xd0, 0x50, 0xf8, 0x28, 0xbc,
	0x3f, 0xfb, 0x89, 0x03, 0xf5, 0x4f, 0x00, 0x5a, 0x2d, 0xe1, 0xb7, 0x89, 0x4f, 0x85, 0x24, 0x7c,
	0x3b, 0x4d, 0x34, 0x1b, 0xf0, 0x0a, 0x27, 0x3d, 0xc2, 0x09, 0xa9, 0x82, 0x5b, 0xe0, 0x5e, 0xa5,
	0x59, 0xfd, 0xf6, 0x79, 0xc3, 0x4a, 0xda, 0xd9, 0xf6, 0x3c, 0x4e, 0x84, 0x78, 0x2e, 0x39, 0x1d,
	0xf9, 0xed, 0x54, 0x68, 0x6e, 0xc2, 0x8a, 0xaa, 0x5c, 0xbd, 0x70, 0x4a, 0x96, 0x96, 0x6e, 0x59,
	0x1f, 0xc6, 0x35, 0xe3, 0xf7, 0xb8, 0x66, 0x1c, 0xfc, 0x3a, 0x5c, 0x4f, 0xdd, 0xea, 0x0e, 0xbc,
	0x99, 0xd7, 0x59, 0x9b, 0x88, 0x80, 0x8d, 0x04, 0xa9, 0x8f, 0x01, 0x5c, 0x6a, 0x09, 0xff, 0x65,
	0xe0, 0x61, 0x49, 0x54, 0xf8, 0x05, 0x25, 0x5c, 0x44, 0x9d, 0xec, 0xca, 0x3e, 0xe3, 0x54, 0xee,
	0x9f, 0xda, 0xbf, 0x96, 0x9a, 0x8f, 0xe1, 0x25, 0x39, 0x33, 0x88, 0xba, 0xbf, 0xda, 0x58, 0x71,
	0x33, 0xf3, 0x71, 0x4f, 0x56, 0x6a, 0x2e, 0x1c, 0xfd, 0xa8, 0x19, 0xed, 0x38, 0x6b, 0xeb, 0xda,
	0x0c, 0x40, 0xdb, 0xd5, 0x57, 0x60, 0x6d, 0x4e, 0x87, 0x8a, 0xe2, 0x10, 0xc0, 0x1b, 0x59, 0xcd,
	0xeb, 0x3e, 0x95, 0x64, 0x40, 0x85, 0x3c, 0x37, 0xc9, 0x13, 0x58, 0x79, 0x97, 0x9a, 0x24, 0x34,
	0xab, 0x45, 0x34, 0xaa, 0x62, 0x42, 0xa4, 0xb3, 0x33, 0x54, 0xab, 0xf0, 0x76, 0x41, 0xc7, 0x8a,
	0xec, 0x2b, 0x88, 0x06, 0xf8, 0x8f, 0xee, 0x19, 0xe6, 0x78, 0x48, 0xe4, 0xff, 0x0c, 0xa9, 0x03,
	0x2d, 0x45, 0xd0, 0x09, 0x94, 0x5f, 0x42, 0xb9, 0x56, 0x44, 0xa9, 0xab, 0x27, 0x98, 0xd7, 0x71,
	0x36, 0x94, 0x01, 0x5e, 0x83, 0x77, 0x8a, 0x40, 0x14, 0xf1, 0x97, 0xdc, 0x59, 0x3e, 0x0d, 0x09,
	0xe7, 0xd4, 0x23, 0xe7, 0x07, 0x7e, 0x0b, 0x75, 0x9b, 0x1d, 0x96, 0xda, 0x95, 0x99, 0xaa, 0xaa,
	0x9d, 0xe0, 0x9a, 0x38, 0x13, 0x29, 0x37, 0x5e, 0x25, 0x4f, 0x61, 0x1b, 0x7f, 0x16, 0xe0, 0xc5,
	0x96, 0xf0, 0xcd, 0x21, 0x5c, 0xcc, 0x7e, 0x3d, 0xee, 0xe6, 0x34, 0x95, 0x77, 0x98, 0x6d, 0x54,
	0x52, 0x98, 0x96, 0x35, 0x43, 0x68, 0xe5, 0x9e, 0xf8, 0xf5, 0x7c, 0xa3, 0x3c, 0xad, 0xdd, 0x28,
	0xaf, 0x55, 0x75, 0x0f, 0x00, 0xac, 0xce, 0x3d, 0xa4, 0x6e, 0x29, 0x43, 0xa5, 0xb7, 0x37, 0xcf,
	0xa6, 0x57, 0x4d, 0xbc, 0x07, 0x70, 0x79, 0xfe, 0x79, 0x42, 0xa5, 0x5c, 0x75, 0x82, 0xfd, 0xf0,
	0x8c, 0x09, 0x45, 0x8b, 0xa1, 0x77, 0x79, 0xb9, 0xc5, 0x50, 0xfa, 0x92, 0x8b, 0x91, 0xd9, 0x80,
	0xcd, 0x57, 0x47, 0x13, 0x07, 0x1c, 0x4f, 0x1c, 0xf0, 0x73, 0xe2, 0x80, 0x8f, 0x53, 0xc7, 0x38,
	0x9e, 0x3a, 0xc6, 0xf7, 0xa9, 0x63, 0xbc, 0x79, 0xe4, 0x53, 0xd9, 0xdf, 0xdd, 0x71, 0xbb, 0x6c,
	0x88, 0x3c, 0x3c, 0xa2, 0x64, 0x90, 0x5c, 0x91, 0xa1, 0xb7, 0xd1, 0xed, 0x63, 0x3a, 0x42, 0xd1,
	0xe5, 0xd7, 0x65, 0x03, 0x74, 0xf2, 0x5a, 0xde, 0x0f, 0x88, 0xd8, 0xb9, 0x1c, 0x05, 0x1f, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x34, 0xbe, 0x27, 0x55, 0xb8, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterAffiliate registers a referee-affiliate relationship
	RegisterAffiliate(ctx context.Context, in *MsgRegisterAffiliate, opts ...grpc.CallOption) (*MsgRegisterAffiliateResponse, error)
	// UpdateAffiliateTiers updates affiliate tiers
	UpdateAffiliateTiers(ctx context.Context, in *MsgUpdateAffiliateTiers, opts ...grpc.CallOption) (*MsgUpdateAffiliateTiersResponse, error)
	// UpdateAffiliateWhitelist updates affiliate whitelist
	UpdateAffiliateWhitelist(ctx context.Context, in *MsgUpdateAffiliateWhitelist, opts ...grpc.CallOption) (*MsgUpdateAffiliateWhitelistResponse, error)
	// UpdateAffiliateParameters updates affiliate program parameters
	UpdateAffiliateParameters(ctx context.Context, in *MsgUpdateAffiliateParameters, opts ...grpc.CallOption) (*MsgUpdateAffiliateParametersResponse, error)
	// UpdateAffiliateOverrides updates affiliate overrides
	UpdateAffiliateOverrides(ctx context.Context, in *MsgUpdateAffiliateOverrides, opts ...grpc.CallOption) (*MsgUpdateAffiliateOverridesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterAffiliate(ctx context.Context, in *MsgRegisterAffiliate, opts ...grpc.CallOption) (*MsgRegisterAffiliateResponse, error) {
	out := new(MsgRegisterAffiliateResponse)
	err := c.cc.Invoke(ctx, "/vindax.affiliates.Msg/RegisterAffiliate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateTiers(ctx context.Context, in *MsgUpdateAffiliateTiers, opts ...grpc.CallOption) (*MsgUpdateAffiliateTiersResponse, error) {
	out := new(MsgUpdateAffiliateTiersResponse)
	err := c.cc.Invoke(ctx, "/vindax.affiliates.Msg/UpdateAffiliateTiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateWhitelist(ctx context.Context, in *MsgUpdateAffiliateWhitelist, opts ...grpc.CallOption) (*MsgUpdateAffiliateWhitelistResponse, error) {
	out := new(MsgUpdateAffiliateWhitelistResponse)
	err := c.cc.Invoke(ctx, "/vindax.affiliates.Msg/UpdateAffiliateWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateParameters(ctx context.Context, in *MsgUpdateAffiliateParameters, opts ...grpc.CallOption) (*MsgUpdateAffiliateParametersResponse, error) {
	out := new(MsgUpdateAffiliateParametersResponse)
	err := c.cc.Invoke(ctx, "/vindax.affiliates.Msg/UpdateAffiliateParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateOverrides(ctx context.Context, in *MsgUpdateAffiliateOverrides, opts ...grpc.CallOption) (*MsgUpdateAffiliateOverridesResponse, error) {
	out := new(MsgUpdateAffiliateOverridesResponse)
	err := c.cc.Invoke(ctx, "/vindax.affiliates.Msg/UpdateAffiliateOverrides", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterAffiliate registers a referee-affiliate relationship
	RegisterAffiliate(context.Context, *MsgRegisterAffiliate) (*MsgRegisterAffiliateResponse, error)
	// UpdateAffiliateTiers updates affiliate tiers
	UpdateAffiliateTiers(context.Context, *MsgUpdateAffiliateTiers) (*MsgUpdateAffiliateTiersResponse, error)
	// UpdateAffiliateWhitelist updates affiliate whitelist
	UpdateAffiliateWhitelist(context.Context, *MsgUpdateAffiliateWhitelist) (*MsgUpdateAffiliateWhitelistResponse, error)
	// UpdateAffiliateParameters updates affiliate program parameters
	UpdateAffiliateParameters(context.Context, *MsgUpdateAffiliateParameters) (*MsgUpdateAffiliateParametersResponse, error)
	// UpdateAffiliateOverrides updates affiliate overrides
	UpdateAffiliateOverrides(context.Context, *MsgUpdateAffiliateOverrides) (*MsgUpdateAffiliateOverridesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterAffiliate(ctx context.Context, req *MsgRegisterAffiliate) (*MsgRegisterAffiliateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAffiliate not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateTiers(ctx context.Context, req *MsgUpdateAffiliateTiers) (*MsgUpdateAffiliateTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateTiers not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateWhitelist(ctx context.Context, req *MsgUpdateAffiliateWhitelist) (*MsgUpdateAffiliateWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateWhitelist not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateParameters(ctx context.Context, req *MsgUpdateAffiliateParameters) (*MsgUpdateAffiliateParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateParameters not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateOverrides(ctx context.Context, req *MsgUpdateAffiliateOverrides) (*MsgUpdateAffiliateOverridesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateOverrides not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterAffiliate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterAffiliate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterAffiliate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vindax.affiliates.Msg/RegisterAffiliate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterAffiliate(ctx, req.(*MsgRegisterAffiliate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateTiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vindax.affiliates.Msg/UpdateAffiliateTiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateTiers(ctx, req.(*MsgUpdateAffiliateTiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vindax.affiliates.Msg/UpdateAffiliateWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateWhitelist(ctx, req.(*MsgUpdateAffiliateWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vindax.affiliates.Msg/UpdateAffiliateParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateParameters(ctx, req.(*MsgUpdateAffiliateParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateOverrides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateOverrides)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateOverrides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vindax.affiliates.Msg/UpdateAffiliateOverrides",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateOverrides(ctx, req.(*MsgUpdateAffiliateOverrides))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vindax.affiliates.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAffiliate",
			Handler:    _Msg_RegisterAffiliate_Handler,
		},
		{
			MethodName: "UpdateAffiliateTiers",
			Handler:    _Msg_UpdateAffiliateTiers_Handler,
		},
		{
			MethodName: "UpdateAffiliateWhitelist",
			Handler:    _Msg_UpdateAffiliateWhitelist_Handler,
		},
		{
			MethodName: "UpdateAffiliateParameters",
			Handler:    _Msg_UpdateAffiliateParameters_Handler,
		},
		{
			MethodName: "UpdateAffiliateOverrides",
			Handler:    _Msg_UpdateAffiliateOverrides_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vindax/affiliates/tx.proto",
}

func (m *MsgRegisterAffiliate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAffiliate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAffiliate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Affiliate) > 0 {
		i -= len(m.Affiliate)
		copy(dAtA[i:], m.Affiliate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Affiliate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Referee) > 0 {
		i -= len(m.Referee)
		copy(dAtA[i:], m.Referee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Referee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterAffiliateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAffiliateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAffiliateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateTiers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateTiers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateTiers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tiers.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateTiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateTiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateTiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateWhitelist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateWhitelist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateWhitelist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Whitelist.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateWhitelistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateWhitelistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateWhitelistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateParameters) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateParameters) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AffiliateParameters.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateParametersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateParametersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateParametersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateOverrides) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateOverrides) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateOverrides) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AffiliateOverrides.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateOverridesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateOverridesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateOverridesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterAffiliate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Referee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Affiliate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterAffiliateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateTiers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Tiers.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateTiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateWhitelist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Whitelist.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateWhitelistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.AffiliateParameters.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateParametersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateOverrides) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.AffiliateOverrides.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateOverridesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterAffiliate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAffiliate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAffiliate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Affiliate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Affiliate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterAffiliateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAffiliateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAffiliateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateTiers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tiers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateTiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateWhitelist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Whitelist.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateWhitelistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateParameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AffiliateParameters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateParametersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateParametersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateParametersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateOverrides) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateOverrides: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateOverrides: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateOverrides", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AffiliateOverrides.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateOverridesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateOverridesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateOverridesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
